export const UPDATE_CODE = 'UPDATE_CODE'
export const REMOVE_CODE = 'REMOVE_POST'
export const SET_CURRENT_CODE = 'SET_CURRENT_CODE'
export const ADD_CODE = 'ADD_POST'
export const LOADING = 'LOADING'

export const SET_CURRENT_FILE = 'SET_CURRENT_FILE'
export const ADD_FILES = 'ADD_FILES'
export const REMOVE_FILES = 'REMOVE_FILES'
export const UPDATE_FILES = 'UPDATE_FILES'
